services:
  example_ui:
    image: python:3.13
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    command: pytest -s -v tests/test_buy.py --alluredir=allure_results
    working_dir: /app