name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run UI-tests via docker-compose
        run: |
          docker-compose up --build --exit-code-from example_ui || true

      - name: Copy logs and screenshots from container
        run: |
          CONTAINER_ID=$(docker ps -aqf "name=example_ui")
          mkdir -p logs screenshots
          docker cp $CONTAINER_ID:/app/logs ./logs || true
          docker cp $CONTAINER_ID:/app/screenshots ./screenshots || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Copy history from gh-pages to allure-results
        run: |
          mkdir -p allure_results/history
          cp -R ./.github/gh-pages/history/* allure_results/history/ || true

      - name: Generate Allure report
        run: |
          docker-compose run --rm example_ui /bin/sh -c \
            "allure generate allure_results --clean -o allure-report"

      - name: Update Allure history
        run: |
          mkdir -p ./.github/gh-pages/history
          cp -R allure-report/history/* ./.github/gh-pages/history/ || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
